camera_name: camera
enable_color: true
rgb_camera:
  color_profile: "320,240,30"   
  color_format: RGB8
  enable_auto_exposure: true

enable_depth: false
enable_infra: false
enable_infra1: false
enable_infra2: false
enable_gyro: false
enable_accel: false
enable_sync: false
enable_rgbd: false

publish_tf: true
tf_publish_rate: 10.0
log_level: fatal
